src/Entity/Experience.php
<?php

namespace App\Entity;

use App\Repository\ExperienceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExperienceRepository::class)]
class Experience
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $started_at = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $ended_at = null;

    #[ORM\Column]
    private ?bool $is_dev = null;

    #[ORM\ManyToMany(targetEntity: Skill::class)]
    private Collection $skill;

    #[ORM\OneToMany(mappedBy: 'experience', targetEntity: Media::class, cascade: ['persist', 'remove'])]
    private Collection $media;

    public function __construct()
    {
        $this->skill = new ArrayCollection();
        $this->media = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): static
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->ended_at;
    }

    public function setEndedAt(?\DateTimeInterface $ended_at): static
    {
        $this->ended_at = $ended_at;

        return $this;
    }

    public function isIsDev(): ?bool
    {
        return $this->is_dev;
    }

    public function setIsDev(bool $is_dev): static
    {
        $this->is_dev = $is_dev;

        return $this;
    }

    /**
     * @return Collection<int, Skill>
     */
    public function getSkill(): Collection
    {
        return $this->skill;
    }

    public function addSkill(Skill $skill): static
    {
        if (!$this->skill->contains($skill)) {
            $this->skill->add($skill);
        }

        return $this;
    }

    public function removeSkill(Skill $skill): static
    {
        $this->skill->removeElement($skill);

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): static
    {
        if (!$this->media->contains($medium)) {
            $this->media->add($medium);
            $medium->setExperience($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): static
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getExperience() === $this) {
                $medium->setExperience(null);
            }
        }

        return $this;
    }
}

src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $create_at = null;

    #[ORM\Column]
    private ?bool $is_perso = null;

    #[ORM\ManyToMany(targetEntity: Skill::class, cascade: ['persist'])]
    private Collection $skill;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Link::class, cascade: ['persist', 'remove'])]
    private Collection $link;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Media::class, cascade: ['persist', 'remove'])]
    private Collection $media;

    public function __construct()
    {
        $this->skill = new ArrayCollection();
        $this->link = new ArrayCollection();
        $this->media = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): static
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function isIsPerso(): ?bool
    {
        return $this->is_perso;
    }

    public function setIsPerso(bool $is_perso): static
    {
        $this->is_perso = $is_perso;

        return $this;
    }

    /**
     * @return Collection<int, Skill>
     */
    public function getSkill(): Collection
    {
        return $this->skill;
    }

    public function addSkill(Skill $skill): static
    {
        if (!$this->skill->contains($skill)) {
            $this->skill->add($skill);
        }

        return $this;
    }

    public function removeSkill(Skill $skill): static
    {
        $this->skill->removeElement($skill);

        return $this;
    }

    /**
     * @return Collection<int, Link>
     */
    public function getLink(): Collection
    {
        return $this->link;
    }

    public function addLink(Link $link): static
    {
        if (!$this->link->contains($link)) {
            $this->link->add($link);
            $link->setProject($this);
        }

        return $this;
    }

    public function removeLink(Link $link): static
    {
        if ($this->link->removeElement($link)) {
            // set the owning side to null (unless already changed)
            if ($link->getProject() === $this) {
                $link->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): static
    {
        if (!$this->media->contains($medium)) {
            $this->media->add($medium);
            $medium->setProject($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): static
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getProject() === $this) {
                $medium->setProject(null);
            }
        }

        return $this;
    }
}

templates/shared/_about.html.twig
<div class="flex flex-row justify-center md:justify-around z-10">
	<div class="md:basis-1/2 md:block xl:basis-1/3">
		<div class="flex flex-column lg:justify-start justify-center lg:ms-52">
			{% if portefolio.title == "Ton job ici" %}
				<img class="mt-5 w-64 rounded-full object-center" src="{{ asset("/assets/" ~ portefolio.imageName) }}" alt="Une photo de profil illustrant l'utilisateur du portefolio.">
			{% else %}
				<img class="mt-5 w-64 rounded-full object-center" src="{{ asset("/uploadedMedia/" ~ portefolio.imageName) }}" alt="Une photo de profil illustrant l'utilisateur du portefolio.">
			{% endif %}
			
		</div>
		<div class="flex flex-row lg:justify-start justify-center lg:ms-44 z-10">
			<a class="absolute top-0 right-0 mt-3 me-3" href="{{ path("app_login") }}">
				<i class="fa-solid fa-gear fa-2x text-gray-500 hover:text-white"></i>
			</a>
			<div class="flex flex-col w-100">
				<h1 class="self-center text-white mt-5 text-5xl">{{ portefolio.name }}</h1>
				<p class="text-white self-center">{{ portefolio.birthday.diff(now).y}}
					Ans</p>
				<h2 class="mt-5 text-xl text-white">{{ portefolio.title }}</h2>
				<h3 class="self-end text-white">{{ portefolio.subtitle }}</h3>
				<button class="contact--btn z-10 shadow-xl dark:shadow-gray-800 bg-transparent hover:bg-blue-500 font-semibold text-lg text-gray-200 hover:text-white py-2 px-4 border border-gray-400 hover:border-transparent rounded sm:mt-44 md:mt-28 mt-28 lg:mt-16">
					<i class="fa-regular fa-envelope text-white me-5"></i>
					Me contacter</button>
			</div>
		</div>
	</div>

	<div class="hidden 2xl:flex shrink flex-col justify-center opacity-50">
		<img class="transition-all duration-300 filter sepia hover:sepia-0" src="{{ asset("assets/img-background.png")}}" alt="Image simple illustrant le déveleoppement web">
	</div>

	<div class="md:block hidden 2xl:basis-1/4 basis-1/2 text-gray-500 2xl:ms-28 ms-10 mt-24 max-h-[32rem] overflow-y-auto z-10">
		<h3 class="mb-5 text-white text-2xl">A propos de moi</h3>
		<p>{{ portefolio.description}}</p>
	</div>
</div>
<div class="left-0 bottom-0 absolute z-10 md:p-10 p-2 text-white text-center w-auto">
	<div class="flex flex-row text-xl items-center justify-center">
		{% if portefolio.available %}
			<i class="fa-solid fa-circle text-lime-700 me-3"></i>
			<p>Disponible</p>
		{% else %}
			<i class="fa-solid fa-circle text-red-700 me-3"></i>
			<p>En poste</p>
		{% endif %}
	</div>
	<p>Sur</p>
	<p>
		{{ portefolio.city[0] }}
		{% if portefolio.city | length() > 1 %}
			/
			{{ portefolio.city[1] }}
		{% endif %}
	</p>
</div>

<div class="hidden md:flex lg:flex xl:flex 2xl:flex flex-row justify-center sm:mt-24 md:mt-20 2xl:mt-44 mt-[3rem]">
	<a href="#nav" class="flex flex-col items-center  text-white z-10">
		<i class="shadow-xl dark:shadow-gray-800 fa-solid fa-circle-chevron-down fa-2x mb-5 text-white hover:text-blue-500 2xl:mt-24"></i>
		<p>En savoir plus...</p>
	</a>
</div>

<div class="right-0 bottom-0 absolute z-10 md:p-10 p-2 text-white text-center">
	<h3>Cv général</h3>
	<a href="{{ asset('uploadedMedia/cv/' ~ portefolio.cvName) }}" target="blank()">
		<button class="rounded border-solid border border-white hover:bg-blue-500 hover:text-white p-3 mt-3 shadow-xl dark:shadow-gray">
			<i class="fa-solid fa-download me-2"></i>
			Cv.pdf
			<i class="fa-solid fa-file-pdf ms-2"></i>
		</button>
	</a>
</div>

<svg class="bottom-0 z-0" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 1440 320" id="about--waves">
	<path fill="#101f47" fill-opacity="1" d="M0,128L10.9,133.3C21.8,139,44,149,65,154.7C87.3,160,109,160,131,165.3C152.7,171,175,181,196,202.7C218.2,224,240,256,262,224C283.6,192,305,96,327,64C349.1,32,371,64,393,85.3C414.5,107,436,117,458,117.3C480,117,502,107,524,106.7C545.5,107,567,117,589,144C610.9,171,633,213,655,192C676.4,171,698,85,720,80C741.8,75,764,149,785,186.7C807.3,224,829,224,851,202.7C872.7,181,895,139,916,133.3C938.2,128,960,160,982,144C1003.6,128,1025,64,1047,74.7C1069.1,85,1091,171,1113,224C1134.5,277,1156,299,1178,288C1200,277,1222,235,1244,208C1265.5,181,1287,171,1309,181.3C1330.9,192,1353,224,1375,202.7C1396.4,181,1418,107,1429,69.3L1440,32L1440,320L1429.1,320C1418.2,320,1396,320,1375,320C1352.7,320,1331,320,1309,320C1287.3,320,1265,320,1244,320C1221.8,320,1200,320,1178,320C1156.4,320,1135,320,1113,320C1090.9,320,1069,320,1047,320C1025.5,320,1004,320,982,320C960,320,938,320,916,320C894.5,320,873,320,851,320C829.1,320,807,320,785,320C763.6,320,742,320,720,320C698.2,320,676,320,655,320C632.7,320,611,320,589,320C567.3,320,545,320,524,320C501.8,320,480,320,458,320C436.4,320,415,320,393,320C370.9,320,349,320,327,320C305.5,320,284,320,262,320C240,320,218,320,196,320C174.5,320,153,320,131,320C109.1,320,87,320,65,320C43.6,320,22,320,11,320L0,320Z"></path>
</svg>

templates/shared/_allCardProjects.html.twig
{% for project in projects %}
	{% include "shared/_cardProject.html.twig" with {"project" : project} %}
{% endfor %}

templates/shared/_cardProject.html.twig
<li class="card--js-item hover:border-x-2 hover:border-white" id="showProject--{{ project.id }}">
	<a href="javascript:void(0)" class="card">
		<img src="{{ asset("uploadedMedia/" ~ project.media[0])}}" class="card__image" alt=""/>
		<div class="card__overlay">
			<div class="card__header">
				<svg class="card__arc" xmlns="http://www.w3.org/2000/svg"><path/></svg>
				<div class="card__header-text">
					<h3 class="card__title">{{ project.name }}</h3>
					<h5 class="text-slate-600">{{ project.createAt | date("Y") }}</h5>
					<span class="card__status"></span>
				</div>
			</div>
			<p class="card__description">{{ project.description }}</p>
		</div>
	</a>
</li>

templates/shared/_contactModal.html.twig
<i class="cursor-pointer fa-solid fa-circle-xmark fa-2x text-white relative flex justify-end" id="contact--div:close"></i>
        <h1 class="text-center text-xl font-bold text-white">Contactez-moi !</h1>
        <div class="mt-5 flex flex-row w-100 text-white">
            {{ form_start(formContact, {"attr" : {"class" : "flex flex-row flex-wrap w-full"}}) }}
                {{ form_label(formContact.emailFrom, "Votre adresse email: ") }}</br>
                {{ form_widget(formContact.emailFrom, {"attr" : {"class" : "flex flex-row w-full text-black p-1"}}) }}</br>

                {{ form_label(formContact.emailSubject, "Sujet du message: ", {"label_attr" : {"class" : "mt-5"}}) }}</br>
                {{ form_widget(formContact.emailSubject, {"attr" : {"class" : "mt-1 flex flex-row w-full text-black p-1"}}) }}</br>

                {{ form_label(formContact.emailContent, "Contenu du message: ", {"label_attr" : {"class" : "mt-5"}}) }}</br>
                {{ form_widget(formContact.emailContent, {"attr" : {"class" : "mt-1 flex flex-row w-full text-black p-1"}}) }}</br>

                <button type="submit" class="mx-auto text-center z-10 shadow-xl dark:shadow-gray-800 bg-transparent hover:bg-blue-500 font-semibold text-lg text-gray-200 hover:text-white py-2 px-4 border-solid border-4 border-gray-400 hover:border-transparent rounded sm:mt-44 md:mt-28 mt-28 lg:mt-16"><i class="fa-regular fa-envelope text-white me-5"></i> Envoyer</button>
            {{ form_end(formContact) }}
        </div>

templates/shared/_experienceTimeline.html.twig
{% for experience in experiences | reverse %}
	<li>
		<div class="border-2 border-white border-solid hover:sepia sepia-0">
			<time class="text-white">{{ experience.startedAt | date("m/Y") }} - {{ experience.endedAt | date("m/Y") }}</time>
			<h3 class="mb-5 text-xl text-white">{{ experience.name }}</h3>
			<img class="mb-5" src="{{ asset("uploadedMedia/" ~ experience.media[0].fileName) }}" alt="Image représentant l'expérience. Comme le logo de l'entreprise par exemple.">
			<p>{{ experience.description }}</p>
		</div>
		<a href="#competence">
			<div class="cursor-pointer border-2 border-white border-solid flex flex-row flex-wrap justify-center text-white max-h-48 overflow-y-auto" id="experience--skill">
				{% for skill in experience.skill %}
					<div class="flex flex-col items-center">
						{{ skill.iconPath | raw }}
						<p>{{ skill.name }}</p>
					</div>
				{% endfor %}
			</div>
		</a>
	</li>
{% endfor %}

templates/shared/_footer.html.twig
<div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
	<span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© {{ 'now' | date('Y') }}
		<a href="/" class="hover:underline">SABIO Florent™</a>. All Rights Reserved.
	</span>
	<ul class="flex flex-wrap justify-center items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
		<li>
			<a href="#about--div" class="mr-4 hover:underline md:mr-6 cursor-pointer ">A propos</a>
		</li>
		<li>
			<p class="contact--btn hover:underline cursor-pointer">Contact</p>
		</li>
		{# <li>
			<a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
		</li>
		<li>
			<a href="#" class="mr-4 hover:underline md:mr-6">Licensing</a>
		</li> #}
	</ul>
</div>

templates/shared/_imageProjectCarousel.html.twig
<div>
	<div class="carousel">
		<ul class="slides">
            {% set mediaCounter = 1 %}
            {% for media in project.media %}
                {% if mediaCounter == 1 %}
                    <input type="radio" name="radio-buttons" id="img-{{ mediaCounter }}" checked/>
                {% else %}
                    <input type="radio" name="radio-buttons" id="img-{{ mediaCounter }}"/>
                {% endif %}
            
                <li class="slide-container">
                    <div class="slide-image mt-20">
                        <img src="{{ asset('uploadedMedia/' ~ media.fileName) }}">
                    </div>
                    <div class="carousel-controls">
                        {% if mediaCounter == 1 %}
                            <label for="img-{{ project.media | length }}" class="prev-slide mt-28">
                                <span>&lsaquo;</span>
                            </label>
                        {% else %}
                            <label for="img-{{ mediaCounter - 1 }}" class="prev-slide mt-28">
                                <span>&lsaquo;</span>
                            </label>
                        {% endif %}
                        
                        {% if mediaCounter == project.media | length %}
                            <label for="img-1" class="next-slide mt-28">
                                <span>&rsaquo;</span>
                            </label>
                        {% else %}
                            <label for="img-{{ mediaCounter + 1 }}" class="next-slide mt-28">
                                <span>&rsaquo;</span>
                            </label>
                        {% endif %}
                    </div>
                </li>
                {% set mediaCounter = mediaCounter + 1 %}
            {% endfor %}
            <div class="carousel-dots">
                {% set mediaCounter = 1 %}
                {% for media in project.media %}
                    <label for="img-{{ mediaCounter }}" class="carousel-dot" id="img-dot-{{ mediaCounter }}"></label>
                    {% set mediaCounter = mediaCounter + 1 %}
                {% endfor %}
            </div>
		</ul>
	</div>
</div>

templates/shared/_nav.html.twig
<nav class="container w-100 border-dashed border-gray-600 border-2 ms-auto me-auto lg:text-2xl p-1" id="nav">
    <div class="flex flex-row justify-around text-white">
        <a href="#projects"><h2 class="p-3 hover:bg-blue-500 rounded border-2 border-transparent hover:border-solid hover:border-white">
            Projets
        </h2></a>
        <a href="#competence"><h2 class="p-3 hover:bg-blue-500 rounded border-2 border-transparent hover:border-solid hover:border-white">
            Compétences
        </h2></a>
        <a href="#experience"><h2 class="p-3 hover:bg-blue-500 rounded border-2 border-transparent hover:border-solid hover:border-white">
            Expériences
        </h2></a>
    </div>
</nav>

templates/shared/_showProject.html.twig
<h1 class="text-white text-2xl font-bold">{{ project.name }}</h1>
<h5 class="text-white">{{ project.createAt | date("Y") }}</h5>
<div class="flex flex-row mt-5">
	<div class="hidden sm:flex flex-col xl:w-5/12 lg:w-4/12 w-9/12 mx-auto mb-1">
		{% include "shared/_imageProjectCarousel.html.twig" %}
	</div>
	<div class="flex flex-col lg:w-7/12 w-full overflow-y-auto p-3">
		<div class="md:h-80 h-72 overflow-y-scroll">
			<p>{{ project.description }}</p>
		</div>
		<div class="flex md:flex-row flex-col 2xl:mt-24 mt-10 h-3/4 ">
			<div class="flex flex-col basis-8/12 h-full overflow-y-auto">
				<div class="flex flex-col items-center h-full border-white border-0 sm:border-b-0 sm:border-r-2">
					<h2 class="text-xl text-white">Skills</h2>
					<div class="mt-2 w-full lg:w-4/6 md:h-full h-28 flex flex-wrap gap-2 overflow-y-auto">
						{% for skill in project.skill %}
							<div class="cursor-pointer hover:border-gray-600 hover:text-gray-600 w-26 flex flex-col items-center justify-center rounded-full p-2 border-solid border-2 border-white text-white">
								<p>{{ skill.name }}</p>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
			<div class="flex flex-col md:w-2/3 w-full h-40 overflow-y-auto md:mt-0 mt-5">
				<h2 class="text-xl text-white text-center">Liens</h2>
				<ul class="lg:p-5 p-1 text-sm lg:text-base">
					{% for link in project.link %}
						<li class="flex flex-row text-gray-800">
							<h4 class="underline">{{ link.linkLabel }}</h4>
							<p>: <a href="{{ link.linkSelf }}" class="hover:sepia sepia-0" target="_blank">{{ link.linkSelf }}</a></p>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>